Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

5. Write a script that checks if a person is eligible to vote (age ≥ 18).Take age as a variable and print the appropriate message.

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [78]:
#create List
Fruits = ["Apple", "Banana", "Orange", "Grape", "Mango","Watermelon", "Papaya"]
print(Fruits)

['Apple', 'Banana', 'Orange', 'Grape', 'Mango', 'Watermelon', 'Papaya']


In [79]:
#Append
Fruits.append('Kiwi')
print(Fruits)

['Apple', 'Banana', 'Orange', 'Grape', 'Mango', 'Watermelon', 'Papaya', 'Kiwi']


In [80]:
#Extende
Fruits.extend(['Pineapple', 'Strawberry'])
print(Fruits)

['Apple', 'Banana', 'Orange', 'Grape', 'Mango', 'Watermelon', 'Papaya', 'Kiwi', 'Pineapple', 'Strawberry']


In [81]:
#Insert
Fruits.insert(2,'Cherry')
print(Fruits)

['Apple', 'Banana', 'Cherry', 'Orange', 'Grape', 'Mango', 'Watermelon', 'Papaya', 'Kiwi', 'Pineapple', 'Strawberry']


In [82]:
#Remove
Fruits.remove('Banana')
print(Fruits)

['Apple', 'Cherry', 'Orange', 'Grape', 'Mango', 'Watermelon', 'Papaya', 'Kiwi', 'Pineapple', 'Strawberry']


In [83]:
#Pop
Fruits.pop()
print(Fruits)

['Apple', 'Cherry', 'Orange', 'Grape', 'Mango', 'Watermelon', 'Papaya', 'Kiwi', 'Pineapple']


In [84]:
#Index
print(Fruits.index('Orange'))

2


In [85]:
#Count
print(Fruits.count('Apple'))

1


In [86]:
#Reverse
Fruits.reverse()
print(Fruits)

['Pineapple', 'Kiwi', 'Papaya', 'Watermelon', 'Mango', 'Grape', 'Orange', 'Cherry', 'Apple']


In [87]:
#Sort
Fruits.sort()
print(Fruits)

['Apple', 'Cherry', 'Grape', 'Kiwi', 'Mango', 'Orange', 'Papaya', 'Pineapple', 'Watermelon']


In [88]:
#Clear
Fruits.clear()
print(Fruits)

[]


In [89]:
#Craete Tuple
Students = ("John", "Alice", "Bob")
print(Students)


('John', 'Alice', 'Bob')


In [90]:
#change Second Name
#Students[1] = "Cynthia"
#We cannot change name here because tuple is immutable

In [91]:
#create Set
Numbers = {1,2,3,4,5,5,6,8,9,10,8,7,5,6,7,8,9,10}
print(Numbers)

#Give this output Because it take value only once.

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [92]:
#create Dist
Person = {
    'Name': 'John',
    'Age': 30,
    'City': 'Mumbai'}
print(Person)

{'Name': 'John', 'Age': 30, 'City': 'Mumbai'}


In [93]:
#update age and add new key email
Person['Age'] = 35
Person['Email'] = 'xyz@mail.com'
print(Person)

{'Name': 'John', 'Age': 35, 'City': 'Mumbai', 'Email': 'xyz@mail.com'}


In [94]:
#if a person is eligible to vote (age ≥ 18)
def check_vote_eligibility(age):
    if age >= 18:
        print("You are eligible to vote.")
    else:
        print("You are not eligible to vote.")
#example
check_vote_eligibility(20)
check_vote_eligibility(16)
check_vote_eligibility(25)


You are eligible to vote.
You are not eligible to vote.
You are eligible to vote.


In [95]:
def print_grade(Mark):
    if Mark >= 90:
        print("A")
    elif Mark >= 75:
        print("B")
    elif Mark >=50:
        print("C")
    else:
        print("Fail")
#example
print_grade(56)
print_grade(78)
print_grade(92)
print_grade(45)

C
B
A
Fail


In [96]:
def check_number(number):
    if number > 0:
        if number % 2 == 0:
            print(f"{number} is positive and even.")
        else:
            print(f"{number} is positive but odd.")
    else:
        if number == 0:
            print(f"{number} is zero.")
        else:
            print(f"{number} is negative.")

# Example usage:
check_number(4)
check_number(7)
check_number(0)
check_number(-3)

4 is positive and even.
7 is positive but odd.
0 is zero.
-3 is negative.


**Section B: Numpy**

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [97]:
import numpy as np

# Creating a scalar using np.array()
scalar_array = np.array(5)

print(scalar_array)
print(f"Type: {type(scalar_array)}")
print(f"Number of dimensions: {scalar_array.ndim}")
print(f"Shape: {scalar_array.shape}")

5
Type: <class 'numpy.ndarray'>
Number of dimensions: 0
Shape: ()


In [98]:
import numpy as np

# A 1D array with values 1 to 5
one_d_array = np.array([1, 2, 3, 4, 5])
print("\n1D array:")
print(one_d_array)
print("Shape of 1D array:", one_d_array.shape)
print("Dimensions of 1D array:", one_d_array.ndim)

# A 2D array (2x3) with values from 10 to 60 in steps of 10
two_d_array = np.array([[10, 20, 30], [40, 50, 60]])
print("\n2D array:")
print(two_d_array)
print("Shape of 2D array:", two_d_array.shape)
print("Dimensions of 2D array:", two_d_array.ndim)


1D array:
[1 2 3 4 5]
Shape of 1D array: (5,)
Dimensions of 1D array: 1

2D array:
[[10 20 30]
 [40 50 60]]
Shape of 2D array: (2, 3)
Dimensions of 2D array: 2


In [99]:
#4x4 Array using randit
import numpy as np
Random_array = np.random.randint(0,100,(4,4))
print(Random_array)
print("\nShape of 2D array:", Random_array.shape)

[[ 8  7 48 11]
 [ 6 92 72  5]
 [81 78  8 91]
 [ 4 75  2 94]]

Shape of 2D array: (4, 4)


In [100]:
import pandas as pd
import numpy as np
Array = np.random.randint(0,100,(3,3))
print("Numpy Array:\n", Array)

df = pd.DataFrame(Array, columns=['A', 'B', 'C'])
print("\nPandas DataFrame with column names:\n", df)

Numpy Array:
 [[62 25 50]
 [31 90  8]
 [30  3 63]]

Pandas DataFrame with column names:
     A   B   C
0  62  25  50
1  31  90   8
2  30   3  63


**Section C: Exploring Pandas**

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [101]:
import pandas as pd
import numpy as np

# Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice', 'Frank', 'Grace', 'Heidi', 'Ivan'],
    'Age': [25, 30, 35, 28, 22, 25, 40, 32, 29, 38],
    'City': ['New York', 'London', 'Paris', 'New York', 'Berlin', 'New York', 'Rome', 'London', 'Paris', 'Berlin'],
    'Salary': [50000, 60000, 75000, np.nan, 55000, 50000, 80000, 62000, np.nan, 70000]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\n")

# Use .info()
print("DataFrame Info:")
df.info()
print("\n")

# Use .describe()
print("DataFrame Description:")
print(df.describe())
print("\n")

# Select 'Name' and 'City' columns
print("Selected 'Name' and 'City' columns:")
print(df[['Name', 'City']])
print("\n")

# Drop 'City' column
df_no_city = df.drop('City', axis=1)
print("DataFrame after dropping 'City' column:")
print(df_no_city)
print("\n")

# Fill any missing values in 'Salary' column with the mean
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)
print("DataFrame after filling missing 'Salary' values with the mean:")
print(df)
print("\n")

# Remove any duplicate rows
df_duplicates = df.drop_duplicates()
print("DataFrame after removing duplicate rows:")
print(df_duplicates)

Original DataFrame:
      Name  Age      City   Salary
0    Alice   25  New York  50000.0
1      Bob   30    London  60000.0
2  Charlie   35     Paris  75000.0
3    David   28  New York      NaN
4      Eve   22    Berlin  55000.0
5    Alice   25  New York  50000.0
6    Frank   40      Rome  80000.0
7    Grace   32    London  62000.0
8    Heidi   29     Paris      NaN
9     Ivan   38    Berlin  70000.0


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


DataFrame Description:
             Age       Salary
count  10.000000      8.00000
mean   30.400000  62750.00000
std     5.872724  11297.91384
min    22.000000  50000.00000
25%    25.75

/tmp/ipython-input-362255422.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)
